/**
 * Registre unique des fonctionnalités vendues.
 * `status` dit la vérité sur ce que fait la case dans le super admin :
 *  - live      : cocher/décocher change vraiment ce que voient les clients
 *  - unlinked  : la fonction existe mais la case ne la contrôle pas encore
 *  - soon      : pas encore développée
 *  - manual    : service humain / infrastructure (pas du code)
 *  - core      : toujours actif
 */
export type FeatureStatus = "live" | "unlinked" | "soon" | "manual" | "core";
export type PlanName = "basique" | "standard" | "premium";

export type FeatureDef = {
  id: string;
  name: string;
  description: string;
  category: string;
  icon: string;
  defaultPlans: PlanName[];
  status: FeatureStatus;
  note?: string;
};

export const FEATURE_REGISTRY: FeatureDef[] = [
  {
    id: "menu-digital",
    name: "Menu digital",
    description: "Menu en ligne avec photos et prix",
    category: "menu",
    icon: "📱",
    defaultPlans: ["basique", "standard", "premium"],
    status: "live",
  },
  {
    id: "menu-10-plats",
    name: "Jusqu'à 10 plats",
    description: "Limite de 10 plats dans le menu",
    category: "menu",
    icon: "🍽️",
    defaultPlans: ["basique"],
    status: "live",
    note: "Limite à 10 plats.",
  },
  {
    id: "menu-30-plats",
    name: "Jusqu'à 30 plats",
    description: "Limite de 30 plats dans le menu",
    category: "menu",
    icon: "🍽️",
    defaultPlans: ["standard", "premium"],
    status: "live",
    note: "Limite à 30 plats.",
  },
  {
    id: "menu-illimite",
    name: "Menu illimité",
    description: "Nombre de plats illimité",
    category: "menu",
    icon: "🍽️",
    defaultPlans: ["premium"],
    status: "live",
    note: "Aucune limite.",
  },
  {
    id: "categories-plats",
    name: "Catégories de plats",
    description: "Organiser les plats par catégories",
    category: "menu",
    icon: "📂",
    defaultPlans: ["standard", "premium"],
    status: "live",
  },
  {
    id: "plats-saisonniers",
    name: "Plats saisonniers",
    description: "Ajouter des plats temporaires",
    category: "menu",
    icon: "🌿",
    defaultPlans: ["premium"],
    status: "soon",
  },
  {
    id: "commande-whatsapp",
    name: "Commande WhatsApp",
    description: "Bouton de commande directe",
    category: "order",
    icon: "💬",
    defaultPlans: ["basique", "standard", "premium"],
    status: "live",
    note: "Affiche/masque les boutons WhatsApp sur le site public.",
  },
  {
    id: "panier-commande",
    name: "Panier de commande",
    description: "Système de panier multi-plats",
    category: "order",
    icon: "🛒",
    defaultPlans: ["standard", "premium"],
    status: "live",
    note: "Affiche/masque le panier de commande sur le site public.",
  },
  {
    id: "historique-commandes",
    name: "Historique des commandes",
    description: "Voir l'historique complet",
    category: "order",
    icon: "📋",
    defaultPlans: ["standard", "premium"],
    status: "live",
    note: "Ouvre la page Commandes du tableau de bord (comme le panier).",
  },
  {
    id: "notifications-commandes",
    name: "Notifications commandes",
    description: "Notification à chaque commande",
    category: "order",
    icon: "🔔",
    defaultPlans: ["premium"],
    status: "live",
  },
  {
    id: "qr-code",
    name: "QR Code restaurant",
    description: "QR code pour accéder au menu",
    category: "qr",
    icon: "📲",
    defaultPlans: ["basique", "standard", "premium"],
    status: "live",
  },
  {
    id: "qr-code-table",
    name: "QR Code par table",
    description: "QR code unique par table",
    category: "qr",
    icon: "🪑",
    defaultPlans: ["standard", "premium"],
    status: "live",
  },
  {
    id: "qr-code-personnalise",
    name: "QR Code personnalisé",
    description: "QR code avec logo et couleurs",
    category: "qr",
    icon: "🎨",
    defaultPlans: ["premium"],
    status: "live",
  },
  {
    id: "reservations-basiques",
    name: "Réservations basiques",
    description: "Formulaire de réservation simple",
    category: "reservation",
    icon: "📅",
    defaultPlans: ["basique"],
    status: "live",
    note: "Ouvre les réservations (site + tableau de bord). Pas de niveau « avancé » distinct.",
  },
  {
    id: "reservations-avancees",
    name: "Réservations avancées",
    description: "Réservations avec choix de table",
    category: "reservation",
    icon: "📅",
    defaultPlans: ["standard", "premium"],
    status: "live",
    note: "Ouvre les réservations (site + tableau de bord). Pas de niveau « avancé » distinct.",
  },
  {
    id: "calendrier-reservations",
    name: "Calendrier des réservations",
    description: "Vue calendrier",
    category: "reservation",
    icon: "🗓️",
    defaultPlans: ["standard", "premium"],
    status: "soon",
  },
  {
    id: "confirmation-auto",
    name: "Confirmation automatique",
    description: "Confirmation auto des réservations",
    category: "reservation",
    icon: "✅",
    defaultPlans: ["premium"],
    status: "soon",
  },
  {
    id: "rappel-reservation",
    name: "Rappel de réservation",
    description: "Rappel SMS/WhatsApp",
    category: "reservation",
    icon: "⏰",
    defaultPlans: ["premium"],
    status: "unlinked",
    note: "Existe en partie dans la messagerie, non relié à la case.",
  },
  {
    id: "template-basique",
    name: "1 Template basique",
    description: "Template Classique uniquement",
    category: "template",
    icon: "🎨",
    defaultPlans: ["basique"],
    status: "live",
    note: "Autorise le template gratuit.",
  },
  {
    id: "template-standard",
    name: "4 Templates Standard",
    description: "Soleil, Savane, Vert, Épuré",
    category: "template",
    icon: "🎨",
    defaultPlans: ["standard"],
    status: "live",
    note: "Autorise les templates Standard.",
  },
  {
    id: "template-premium",
    name: "4 Templates Premium",
    description: "Templates avec animations",
    category: "template",
    icon: "✨",
    defaultPlans: ["premium"],
    status: "live",
    note: "Autorise les templates Premium.",
  },
  {
    id: "personnalisation-couleurs",
    name: "Personnalisation couleurs",
    description: "Changer les couleurs",
    category: "template",
    icon: "🎨",
    defaultPlans: ["standard", "premium"],
    status: "live",
    note: "Appliqué sur les 4 templates Standard (pas encore sur les Premium).",
  },
  {
    id: "personnalisation-police",
    name: "Personnalisation police",
    description: "Changer la police",
    category: "template",
    icon: "✏️",
    defaultPlans: ["premium"],
    status: "live",
    note: "Appliqué sur les 4 templates Standard (pas encore sur les Premium).",
  },
  {
    id: "stats-essentielles",
    name: "Statistiques essentielles",
    description: "Vues et commandes de base",
    category: "stats",
    icon: "📊",
    defaultPlans: ["basique"],
    status: "live",
    note: "Cartes de chiffres clés.",
  },
  {
    id: "stats-basiques",
    name: "Statistiques basiques",
    description: "Statistiques détaillées",
    category: "stats",
    icon: "📊",
    defaultPlans: ["standard"],
    status: "live",
    note: "Graphiques de revenus / commandes.",
  },
  {
    id: "stats-avancees",
    name: "Statistiques avancées",
    description: "Analytics complets",
    category: "stats",
    icon: "📈",
    defaultPlans: ["premium"],
    status: "live",
    note: "Tout + jours de la semaine + ticket moyen.",
  },
  {
    id: "stats-ventes",
    name: "Statistiques des ventes",
    description: "Analyse des ventes",
    category: "stats",
    icon: "💰",
    defaultPlans: ["premium"],
    status: "live",
    note: "Top des articles vendus.",
  },
  {
    id: "stats-clients",
    name: "Statistiques clients",
    description: "Analyse comportement clients",
    category: "stats",
    icon: "👥",
    defaultPlans: ["premium"],
    status: "live",
    note: "Heures de pointe.",
  },
  {
    id: "export-statistiques",
    name: "Export statistiques",
    description: "Exporter PDF/Excel",
    category: "stats",
    icon: "📥",
    defaultPlans: ["premium"],
    status: "live",
  },
  {
    id: "galerie-photos",
    name: "Galerie photos",
    description: "Jusqu'à 10 photos",
    category: "gallery",
    icon: "🖼️",
    defaultPlans: ["standard", "premium"],
    status: "live",
  },
  {
    id: "galerie-illimitee",
    name: "Galerie illimitée",
    description: "Photos illimitées",
    category: "gallery",
    icon: "🖼️",
    defaultPlans: ["premium"],
    status: "live",
    note: "Sinon 12 photos maximum.",
  },
  {
    id: "galerie-videos",
    name: "Galerie vidéos",
    description: "Ajouter des vidéos",
    category: "gallery",
    icon: "🎬",
    defaultPlans: ["premium"],
    status: "live",
    note: "Vidéos sur le site et le tableau de bord (6 max, 40 Mo).",
  },
  {
    id: "avis-clients",
    name: "Avis clients",
    description: "Système d'avis et témoignages",
    category: "reviews",
    icon: "⭐",
    defaultPlans: ["standard", "premium"],
    status: "live",
  },
  {
    id: "repondre-avis",
    name: "Répondre aux avis",
    description: "Répondre aux avis clients",
    category: "reviews",
    icon: "💬",
    defaultPlans: ["premium"],
    status: "live",
  },
  {
    id: "avis-google",
    name: "Avis Google intégrés",
    description: "Afficher les avis Google",
    category: "reviews",
    icon: "🔗",
    defaultPlans: ["premium"],
    status: "soon",
  },
  {
    id: "facturation-pdf",
    name: "Facturation PDF basique",
    description: "Factures simples",
    category: "billing",
    icon: "🧾",
    defaultPlans: ["standard"],
    status: "live",
    note: "Ouvre la page Facturation.",
  },
  {
    id: "facturation-logo",
    name: "Facturation PDF + logo",
    description: "Factures avec logo",
    category: "billing",
    icon: "🧾",
    defaultPlans: ["premium"],
    status: "live",
    note: "Logo sur les factures PDF.",
  },
  {
    id: "facture-auto",
    name: "Facturation automatique",
    description: "Génération automatique",
    category: "billing",
    icon: "⚡",
    defaultPlans: ["premium"],
    status: "soon",
  },
  {
    id: "devis",
    name: "Devis en ligne",
    description: "Créer et envoyer des devis",
    category: "billing",
    icon: "📄",
    defaultPlans: ["premium"],
    status: "soon",
  },
  {
    id: "gestion-employes",
    name: "Gestion employés",
    description: "Ajout de staff avec rôles",
    category: "staff",
    icon: "👥",
    defaultPlans: ["premium"],
    status: "live",
  },
  {
    id: "login-staff-pin",
    name: "Connexion staff par PIN",
    description: "Employés se connectent par PIN",
    category: "staff",
    icon: "🔑",
    defaultPlans: ["premium"],
    status: "unlinked",
    note: "Existe mais la case ne le contrôle pas encore.",
  },
  {
    id: "espace-cuisine",
    name: "Espace cuisine",
    description: "Interface cuisine avec minuteur",
    category: "staff",
    icon: "👨‍🍳",
    defaultPlans: ["premium"],
    status: "live",
  },
  {
    id: "planning-staff",
    name: "Planning du staff",
    description: "Gérer les horaires",
    category: "staff",
    icon: "📋",
    defaultPlans: ["premium"],
    status: "soon",
  },
  {
    id: "plan-salle",
    name: "Plan de salle interactif",
    description: "Gérer les tables",
    category: "tables",
    icon: "🪑",
    defaultPlans: ["standard", "premium"],
    status: "live",
    note: "Ouvre la page Tables du tableau de bord.",
  },
  {
    id: "etat-tables",
    name: "État des tables",
    description: "Tables libres/occupées en temps réel",
    category: "tables",
    icon: "🟢",
    defaultPlans: ["standard", "premium"],
    status: "live",
    note: "Ouvre la page Tables du tableau de bord.",
  },
  {
    id: "reservation-table",
    name: "Réservation par table",
    description: "Assigner une table",
    category: "tables",
    icon: "📌",
    defaultPlans: ["premium"],
    status: "unlinked",
    note: "Existe en partie, la case ne le contrôle pas encore.",
  },
  {
    id: "chat-interne",
    name: "Chat interne",
    description: "Communication cuisinier ↔ serveur",
    category: "chat",
    icon: "💬",
    defaultPlans: ["standard", "premium"],
    status: "live",
  },
  {
    id: "notifications-chat",
    name: "Notifications chat",
    description: "Notifications sonores",
    category: "chat",
    icon: "🔔",
    defaultPlans: ["premium"],
    status: "unlinked",
    note: "Son du chat existant, non relié à la case.",
  },
  {
    id: "chat-fichiers",
    name: "Partage de fichiers",
    description: "Envoyer photos et fichiers",
    category: "chat",
    icon: "📎",
    defaultPlans: ["premium"],
    status: "soon",
  },
  {
    id: "promotions",
    name: "Promotions",
    description: "Codes promo et réductions",
    category: "marketing",
    icon: "🏷️",
    defaultPlans: ["premium"],
    status: "soon",
  },
  {
    id: "campagnes-whatsapp",
    name: "Campagnes WhatsApp",
    description: "Envoyer des offres",
    category: "marketing",
    icon: "📢",
    defaultPlans: ["premium"],
    status: "soon",
  },
  {
    id: "fidelite",
    name: "Programme de fidélité",
    description: "Carte de fidélité digitale",
    category: "marketing",
    icon: "💎",
    defaultPlans: ["premium"],
    status: "soon",
  },
  {
    id: "reseaux-sociaux",
    name: "Liens réseaux sociaux",
    description: "Facebook, Instagram",
    category: "marketing",
    icon: "🌐",
    defaultPlans: ["standard", "premium"],
    status: "live",
    note: "Liens affichés sur les templates Standard.",
  },
  {
    id: "gestion-stocks",
    name: "Gestion des stocks",
    description: "Suivi des ingrédients",
    category: "stock",
    icon: "📦",
    defaultPlans: ["standard", "premium"],
    status: "live",
  },
  {
    id: "alertes-stocks",
    name: "Alertes stocks bas",
    description: "Notification stock faible",
    category: "stock",
    icon: "⚠️",
    defaultPlans: ["standard", "premium"],
    status: "unlinked",
    note: "Existe, non relié à la case.",
  },
  {
    id: "fournisseurs",
    name: "Gestion fournisseurs",
    description: "Liste des fournisseurs",
    category: "stock",
    icon: "🚚",
    defaultPlans: ["premium"],
    status: "soon",
  },
  {
    id: "messagerie-whatsapp",
    name: "Messagerie WhatsApp",
    description: "Gérer les conversations",
    category: "messaging",
    icon: "💬",
    defaultPlans: ["standard", "premium"],
    status: "live",
  },
  {
    id: "reponses-rapides",
    name: "Réponses rapides",
    description: "Modèles de messages",
    category: "messaging",
    icon: "⚡",
    defaultPlans: ["premium"],
    status: "soon",
  },
  {
    id: "broadcast",
    name: "Diffusion groupée",
    description: "Envoyer à tous les clients",
    category: "messaging",
    icon: "📨",
    defaultPlans: ["premium"],
    status: "soon",
  },
  {
    id: "parametres-site",
    name: "Paramètres du site",
    description: "Modifier les infos",
    category: "settings",
    icon: "⚙️",
    defaultPlans: ["basique", "standard", "premium"],
    status: "core",
    note: "Toujours actif, ne peut pas être retiré.",
  },
  {
    id: "logo-personnalise",
    name: "Logo personnalisé",
    description: "Ajouter le logo",
    category: "settings",
    icon: "🖼️",
    defaultPlans: ["standard", "premium"],
    status: "live",
    note: "Logo du site public.",
  },
  {
    id: "domaine-personnalise",
    name: "Nom de domaine",
    description: "Domaine personnalisé",
    category: "settings",
    icon: "🌐",
    defaultPlans: ["premium"],
    status: "manual",
    note: "Service manuel (DNS) : à faire par vous.",
  },
  {
    id: "mode-sombre",
    name: "Mode sombre",
    description: "Thème sombre",
    category: "settings",
    icon: "🌙",
    defaultPlans: ["standard", "premium"],
    status: "soon",
  },
  {
    id: "theme-neon",
    name: "Thème Néon",
    description: "Mode néon",
    category: "settings",
    icon: "💡",
    defaultPlans: ["premium"],
    status: "soon",
  },
  {
    id: "theme-jour",
    name: "Thème Jour",
    description: "Mode clair",
    category: "settings",
    icon: "☀️",
    defaultPlans: ["standard", "premium"],
    status: "soon",
  },
  {
    id: "contenu-branding",
    name: "Contenu & branding",
    description: "Personnaliser le contenu",
    category: "settings",
    icon: "🖌️",
    defaultPlans: ["standard", "premium"],
    status: "live",
    note: "Titre, sous-titre et texte « à propos » : templates Standard uniquement.",
  },
  {
    id: "apercu-dashboard",
    name: "Aperçu du dashboard",
    description: "Page d'accueil",
    category: "settings",
    icon: "📊",
    defaultPlans: ["basique", "standard", "premium"],
    status: "core",
    note: "Toujours actif, ne peut pas être retiré.",
  },
  {
    id: "support-prioritaire",
    name: "Support prioritaire",
    description: "Support WhatsApp dédié",
    category: "support",
    icon: "🎧",
    defaultPlans: ["premium"],
    status: "manual",
    note: "Service humain : à gérer par vous.",
  },
  {
    id: "support-standard",
    name: "Support standard",
    description: "Support par email",
    category: "support",
    icon: "📧",
    defaultPlans: ["standard"],
    status: "manual",
    note: "Service humain : à gérer par vous.",
  },
  {
    id: "formation",
    name: "Formation en ligne",
    description: "Guide et tutoriels",
    category: "support",
    icon: "📚",
    defaultPlans: ["standard", "premium"],
    status: "manual",
    note: "Contenu à produire.",
  },
  {
    id: "rapports-mensuels",
    name: "Rapports mensuels",
    description: "Rapports PDF automatiques",
    category: "reports",
    icon: "📄",
    defaultPlans: ["premium"],
    status: "live",
  },
  {
    id: "rapports-ventes",
    name: "Rapports de ventes",
    description: "Analyse des ventes",
    category: "reports",
    icon: "📊",
    defaultPlans: ["premium"],
    status: "live",
  },
  {
    id: "export-donnees",
    name: "Export des données",
    description: "Exporter en CSV",
    category: "reports",
    icon: "💾",
    defaultPlans: ["premium"],
    status: "live",
  },
];

export const FEATURE_BY_ID: Record<string, FeatureDef> = Object.fromEntries(
  FEATURE_REGISTRY.map((f) => [f.id, f]),
);
