/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as AuthInscriptionRouteImport } from './routes/auth/inscription'
import { Route as AuthConnexionRouteImport } from './routes/auth/connexion'
import { Route as AuthChoisirTemplateRouteImport } from './routes/auth/choisir-template'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardTablesRouteImport } from './routes/_authenticated/dashboard.tables'
import { Route as AuthenticatedDashboardReservationsRouteImport } from './routes/_authenticated/dashboard.reservations'
import { Route as AuthenticatedDashboardQrCodeRouteImport } from './routes/_authenticated/dashboard.qr-code'
import { Route as AuthenticatedDashboardParametresRouteImport } from './routes/_authenticated/dashboard.parametres'
import { Route as AuthenticatedDashboardMenuRouteImport } from './routes/_authenticated/dashboard.menu'
import { Route as AuthenticatedDashboardGalerieRouteImport } from './routes/_authenticated/dashboard.galerie'
import { Route as AuthenticatedDashboardFacturationRouteImport } from './routes/_authenticated/dashboard.facturation'
import { Route as AuthenticatedDashboardContenuRouteImport } from './routes/_authenticated/dashboard.contenu'
import { Route as AuthenticatedDashboardCommandesRouteImport } from './routes/_authenticated/dashboard.commandes'
import { Route as AuthenticatedDashboardAvisRouteImport } from './routes/_authenticated/dashboard.avis'

const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthInscriptionRoute = AuthInscriptionRouteImport.update({
  id: '/auth/inscription',
  path: '/auth/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConnexionRoute = AuthConnexionRouteImport.update({
  id: '/auth/connexion',
  path: '/auth/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthChoisirTemplateRoute = AuthChoisirTemplateRouteImport.update({
  id: '/auth/choisir-template',
  path: '/auth/choisir-template',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardTablesRoute =
  AuthenticatedDashboardTablesRouteImport.update({
    id: '/tables',
    path: '/tables',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardReservationsRoute =
  AuthenticatedDashboardReservationsRouteImport.update({
    id: '/reservations',
    path: '/reservations',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardQrCodeRoute =
  AuthenticatedDashboardQrCodeRouteImport.update({
    id: '/qr-code',
    path: '/qr-code',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardParametresRoute =
  AuthenticatedDashboardParametresRouteImport.update({
    id: '/parametres',
    path: '/parametres',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMenuRoute =
  AuthenticatedDashboardMenuRouteImport.update({
    id: '/menu',
    path: '/menu',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardGalerieRoute =
  AuthenticatedDashboardGalerieRouteImport.update({
    id: '/galerie',
    path: '/galerie',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardFacturationRoute =
  AuthenticatedDashboardFacturationRouteImport.update({
    id: '/facturation',
    path: '/facturation',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardContenuRoute =
  AuthenticatedDashboardContenuRouteImport.update({
    id: '/contenu',
    path: '/contenu',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCommandesRoute =
  AuthenticatedDashboardCommandesRouteImport.update({
    id: '/commandes',
    path: '/commandes',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAvisRoute =
  AuthenticatedDashboardAvisRouteImport.update({
    id: '/avis',
    path: '/avis',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/super-admin': typeof SuperAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/auth/choisir-template': typeof AuthChoisirTemplateRoute
  '/auth/connexion': typeof AuthConnexionRoute
  '/auth/inscription': typeof AuthInscriptionRoute
  '/r/$slug': typeof RSlugRoute
  '/dashboard/avis': typeof AuthenticatedDashboardAvisRoute
  '/dashboard/commandes': typeof AuthenticatedDashboardCommandesRoute
  '/dashboard/contenu': typeof AuthenticatedDashboardContenuRoute
  '/dashboard/facturation': typeof AuthenticatedDashboardFacturationRoute
  '/dashboard/galerie': typeof AuthenticatedDashboardGalerieRoute
  '/dashboard/menu': typeof AuthenticatedDashboardMenuRoute
  '/dashboard/parametres': typeof AuthenticatedDashboardParametresRoute
  '/dashboard/qr-code': typeof AuthenticatedDashboardQrCodeRoute
  '/dashboard/reservations': typeof AuthenticatedDashboardReservationsRoute
  '/dashboard/tables': typeof AuthenticatedDashboardTablesRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/super-admin': typeof SuperAdminRoute
  '/auth/choisir-template': typeof AuthChoisirTemplateRoute
  '/auth/connexion': typeof AuthConnexionRoute
  '/auth/inscription': typeof AuthInscriptionRoute
  '/r/$slug': typeof RSlugRoute
  '/dashboard/avis': typeof AuthenticatedDashboardAvisRoute
  '/dashboard/commandes': typeof AuthenticatedDashboardCommandesRoute
  '/dashboard/contenu': typeof AuthenticatedDashboardContenuRoute
  '/dashboard/facturation': typeof AuthenticatedDashboardFacturationRoute
  '/dashboard/galerie': typeof AuthenticatedDashboardGalerieRoute
  '/dashboard/menu': typeof AuthenticatedDashboardMenuRoute
  '/dashboard/parametres': typeof AuthenticatedDashboardParametresRoute
  '/dashboard/qr-code': typeof AuthenticatedDashboardQrCodeRoute
  '/dashboard/reservations': typeof AuthenticatedDashboardReservationsRoute
  '/dashboard/tables': typeof AuthenticatedDashboardTablesRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/super-admin': typeof SuperAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/auth/choisir-template': typeof AuthChoisirTemplateRoute
  '/auth/connexion': typeof AuthConnexionRoute
  '/auth/inscription': typeof AuthInscriptionRoute
  '/r/$slug': typeof RSlugRoute
  '/_authenticated/dashboard/avis': typeof AuthenticatedDashboardAvisRoute
  '/_authenticated/dashboard/commandes': typeof AuthenticatedDashboardCommandesRoute
  '/_authenticated/dashboard/contenu': typeof AuthenticatedDashboardContenuRoute
  '/_authenticated/dashboard/facturation': typeof AuthenticatedDashboardFacturationRoute
  '/_authenticated/dashboard/galerie': typeof AuthenticatedDashboardGalerieRoute
  '/_authenticated/dashboard/menu': typeof AuthenticatedDashboardMenuRoute
  '/_authenticated/dashboard/parametres': typeof AuthenticatedDashboardParametresRoute
  '/_authenticated/dashboard/qr-code': typeof AuthenticatedDashboardQrCodeRoute
  '/_authenticated/dashboard/reservations': typeof AuthenticatedDashboardReservationsRoute
  '/_authenticated/dashboard/tables': typeof AuthenticatedDashboardTablesRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/super-admin'
    | '/dashboard'
    | '/auth/choisir-template'
    | '/auth/connexion'
    | '/auth/inscription'
    | '/r/$slug'
    | '/dashboard/avis'
    | '/dashboard/commandes'
    | '/dashboard/contenu'
    | '/dashboard/facturation'
    | '/dashboard/galerie'
    | '/dashboard/menu'
    | '/dashboard/parametres'
    | '/dashboard/qr-code'
    | '/dashboard/reservations'
    | '/dashboard/tables'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/super-admin'
    | '/auth/choisir-template'
    | '/auth/connexion'
    | '/auth/inscription'
    | '/r/$slug'
    | '/dashboard/avis'
    | '/dashboard/commandes'
    | '/dashboard/contenu'
    | '/dashboard/facturation'
    | '/dashboard/galerie'
    | '/dashboard/menu'
    | '/dashboard/parametres'
    | '/dashboard/qr-code'
    | '/dashboard/reservations'
    | '/dashboard/tables'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/super-admin'
    | '/_authenticated/dashboard'
    | '/auth/choisir-template'
    | '/auth/connexion'
    | '/auth/inscription'
    | '/r/$slug'
    | '/_authenticated/dashboard/avis'
    | '/_authenticated/dashboard/commandes'
    | '/_authenticated/dashboard/contenu'
    | '/_authenticated/dashboard/facturation'
    | '/_authenticated/dashboard/galerie'
    | '/_authenticated/dashboard/menu'
    | '/_authenticated/dashboard/parametres'
    | '/_authenticated/dashboard/qr-code'
    | '/_authenticated/dashboard/reservations'
    | '/_authenticated/dashboard/tables'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SuperAdminRoute: typeof SuperAdminRoute
  AuthChoisirTemplateRoute: typeof AuthChoisirTemplateRoute
  AuthConnexionRoute: typeof AuthConnexionRoute
  AuthInscriptionRoute: typeof AuthInscriptionRoute
  RSlugRoute: typeof RSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/inscription': {
      id: '/auth/inscription'
      path: '/auth/inscription'
      fullPath: '/auth/inscription'
      preLoaderRoute: typeof AuthInscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/connexion': {
      id: '/auth/connexion'
      path: '/auth/connexion'
      fullPath: '/auth/connexion'
      preLoaderRoute: typeof AuthConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/choisir-template': {
      id: '/auth/choisir-template'
      path: '/auth/choisir-template'
      fullPath: '/auth/choisir-template'
      preLoaderRoute: typeof AuthChoisirTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/tables': {
      id: '/_authenticated/dashboard/tables'
      path: '/tables'
      fullPath: '/dashboard/tables'
      preLoaderRoute: typeof AuthenticatedDashboardTablesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/reservations': {
      id: '/_authenticated/dashboard/reservations'
      path: '/reservations'
      fullPath: '/dashboard/reservations'
      preLoaderRoute: typeof AuthenticatedDashboardReservationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/qr-code': {
      id: '/_authenticated/dashboard/qr-code'
      path: '/qr-code'
      fullPath: '/dashboard/qr-code'
      preLoaderRoute: typeof AuthenticatedDashboardQrCodeRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/parametres': {
      id: '/_authenticated/dashboard/parametres'
      path: '/parametres'
      fullPath: '/dashboard/parametres'
      preLoaderRoute: typeof AuthenticatedDashboardParametresRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/menu': {
      id: '/_authenticated/dashboard/menu'
      path: '/menu'
      fullPath: '/dashboard/menu'
      preLoaderRoute: typeof AuthenticatedDashboardMenuRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/galerie': {
      id: '/_authenticated/dashboard/galerie'
      path: '/galerie'
      fullPath: '/dashboard/galerie'
      preLoaderRoute: typeof AuthenticatedDashboardGalerieRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/facturation': {
      id: '/_authenticated/dashboard/facturation'
      path: '/facturation'
      fullPath: '/dashboard/facturation'
      preLoaderRoute: typeof AuthenticatedDashboardFacturationRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/contenu': {
      id: '/_authenticated/dashboard/contenu'
      path: '/contenu'
      fullPath: '/dashboard/contenu'
      preLoaderRoute: typeof AuthenticatedDashboardContenuRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/commandes': {
      id: '/_authenticated/dashboard/commandes'
      path: '/commandes'
      fullPath: '/dashboard/commandes'
      preLoaderRoute: typeof AuthenticatedDashboardCommandesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/avis': {
      id: '/_authenticated/dashboard/avis'
      path: '/avis'
      fullPath: '/dashboard/avis'
      preLoaderRoute: typeof AuthenticatedDashboardAvisRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAvisRoute: typeof AuthenticatedDashboardAvisRoute
  AuthenticatedDashboardCommandesRoute: typeof AuthenticatedDashboardCommandesRoute
  AuthenticatedDashboardContenuRoute: typeof AuthenticatedDashboardContenuRoute
  AuthenticatedDashboardFacturationRoute: typeof AuthenticatedDashboardFacturationRoute
  AuthenticatedDashboardGalerieRoute: typeof AuthenticatedDashboardGalerieRoute
  AuthenticatedDashboardMenuRoute: typeof AuthenticatedDashboardMenuRoute
  AuthenticatedDashboardParametresRoute: typeof AuthenticatedDashboardParametresRoute
  AuthenticatedDashboardQrCodeRoute: typeof AuthenticatedDashboardQrCodeRoute
  AuthenticatedDashboardReservationsRoute: typeof AuthenticatedDashboardReservationsRoute
  AuthenticatedDashboardTablesRoute: typeof AuthenticatedDashboardTablesRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAvisRoute: AuthenticatedDashboardAvisRoute,
    AuthenticatedDashboardCommandesRoute: AuthenticatedDashboardCommandesRoute,
    AuthenticatedDashboardContenuRoute: AuthenticatedDashboardContenuRoute,
    AuthenticatedDashboardFacturationRoute:
      AuthenticatedDashboardFacturationRoute,
    AuthenticatedDashboardGalerieRoute: AuthenticatedDashboardGalerieRoute,
    AuthenticatedDashboardMenuRoute: AuthenticatedDashboardMenuRoute,
    AuthenticatedDashboardParametresRoute:
      AuthenticatedDashboardParametresRoute,
    AuthenticatedDashboardQrCodeRoute: AuthenticatedDashboardQrCodeRoute,
    AuthenticatedDashboardReservationsRoute:
      AuthenticatedDashboardReservationsRoute,
    AuthenticatedDashboardTablesRoute: AuthenticatedDashboardTablesRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SuperAdminRoute: SuperAdminRoute,
  AuthChoisirTemplateRoute: AuthChoisirTemplateRoute,
  AuthConnexionRoute: AuthConnexionRoute,
  AuthInscriptionRoute: AuthInscriptionRoute,
  RSlugRoute: RSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
